package com.lianglliu.hermoodbarometer.core.designsystem.theme

import androidx.compose.material3.darkColorScheme
import androidx.compose.material3.lightColorScheme
import androidx.compose.ui.graphics.Color

// ==================== Warm Sun (暖阳) ====================

val WarmLightColorScheme =
    lightColorScheme(
        primary = Color(0xFFC4735B),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFFF0EB),
        onPrimaryContainer = Color(0xFF5C2E1E),
        secondary = Color(0xFF7A9E7E),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFEFF5F0),
        onSecondaryContainer = Color(0xFF2E4430),
        tertiary = Color(0xFFC9A84C),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFDF8EC),
        onTertiaryContainer = Color(0xFF4A3D12),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFBF8F4),
        onBackground = Color(0xFF2C2520),
        surface = Color(0xFFFBF8F4),
        onSurface = Color(0xFF2C2520),
        surfaceVariant = Color(0xFFF3EDE7),
        onSurfaceVariant = Color(0xFF524A44),
        outline = Color(0xFF857A72),
        outlineVariant = Color(0xFFD8CFC7),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF383230),
        inverseOnSurface = Color(0xFFF5EEEA),
        inversePrimary = Color(0xFFE8B4A2),
        surfaceDim = Color(0xFFE0D9D3),
        surfaceBright = Color(0xFFFBF8F4),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF7F2ED),
        surfaceContainer = Color(0xFFF3EDE7),
        surfaceContainerHigh = Color(0xFFEDE7E1),
        surfaceContainerHighest = Color(0xFFE7E1DB),
    )

val WarmDarkColorScheme =
    darkColorScheme(
        primary = Color(0xFFD8896F),
        onPrimary = Color(0xFF3E1C0D),
        primaryContainer = Color(0xFF5C2E1E),
        onPrimaryContainer = Color(0xFFFFF0EB),
        secondary = Color(0xFFC5DBC7),
        onSecondary = Color(0xFF1A3320),
        secondaryContainer = Color(0xFF2E4430),
        onSecondaryContainer = Color(0xFFEFF5F0),
        tertiary = Color(0xFFE8D9A0),
        onTertiary = Color(0xFF3A2F08),
        tertiaryContainer = Color(0xFF4A3D12),
        onTertiaryContainer = Color(0xFFFDF8EC),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF1A1714),
        onBackground = Color(0xFFEDE6DD),
        surface = Color(0xFF1A1714),
        onSurface = Color(0xFFEDE6DD),
        surfaceVariant = Color(0xFF3E3832),
        onSurfaceVariant = Color(0xFFD8CFC7),
        outline = Color(0xFF9E958C),
        outlineVariant = Color(0xFF3E3832),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFEDE6DD),
        inverseOnSurface = Color(0xFF383230),
        inversePrimary = Color(0xFFC4735B),
        surfaceDim = Color(0xFF1A1714),
        surfaceBright = Color(0xFF423934),
        surfaceContainerLowest = Color(0xFF14110F),
        surfaceContainerLow = Color(0xFF231F1C),
        surfaceContainer = Color(0xFF272320),
        surfaceContainerHigh = Color(0xFF322D2A),
        surfaceContainerHighest = Color(0xFF3D3835),
    )

// ==================== Azure Sea (碧海) ====================

val OceanLightColorScheme =
    lightColorScheme(
        primary = Color(0xFF3D8FA0),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFE8F4F7),
        onPrimaryContainer = Color(0xFF163840),
        secondary = Color(0xFF5BA88E),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFEBF5F0),
        onSecondaryContainer = Color(0xFF1E4030),
        tertiary = Color(0xFFD4946B),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFDF2EB),
        onTertiaryContainer = Color(0xFF4A3020),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFF4F8FA),
        onBackground = Color(0xFF1C2830),
        surface = Color(0xFFF4F8FA),
        onSurface = Color(0xFF1C2830),
        surfaceVariant = Color(0xFFE6EEF2),
        onSurfaceVariant = Color(0xFF404A50),
        outline = Color(0xFF707A80),
        outlineVariant = Color(0xFFCED8DE),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF303A42),
        inverseOnSurface = Color(0xFFECF2F6),
        inversePrimary = Color(0xFF8DC4D0),
        surfaceDim = Color(0xFFD4DCE0),
        surfaceBright = Color(0xFFF4F8FA),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFEEF4F7),
        surfaceContainer = Color(0xFFE8EEF2),
        surfaceContainerHigh = Color(0xFFE2E8EC),
        surfaceContainerHighest = Color(0xFFDCE2E6),
    )

val OceanDarkColorScheme =
    darkColorScheme(
        primary = Color(0xFF52A8BA),
        onPrimary = Color(0xFF0A2E36),
        primaryContainer = Color(0xFF163840),
        onPrimaryContainer = Color(0xFFE8F4F7),
        secondary = Color(0xFFA8D6C4),
        onSecondary = Color(0xFF0C3020),
        secondaryContainer = Color(0xFF1E4030),
        onSecondaryContainer = Color(0xFFEBF5F0),
        tertiary = Color(0xFFE8C4A8),
        onTertiary = Color(0xFF3A2010),
        tertiaryContainer = Color(0xFF4A3020),
        onTertiaryContainer = Color(0xFFFDF2EB),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF121A1E),
        onBackground = Color(0xFFDDE8EE),
        surface = Color(0xFF121A1E),
        onSurface = Color(0xFFDDE8EE),
        surfaceVariant = Color(0xFF2E3840),
        onSurfaceVariant = Color(0xFFCED8DE),
        outline = Color(0xFF8A949A),
        outlineVariant = Color(0xFF2E3840),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFDDE8EE),
        inverseOnSurface = Color(0xFF303A42),
        inversePrimary = Color(0xFF3D8FA0),
        surfaceDim = Color(0xFF121A1E),
        surfaceBright = Color(0xFF384248),
        surfaceContainerLowest = Color(0xFF0C1418),
        surfaceContainerLow = Color(0xFF1A2228),
        surfaceContainer = Color(0xFF1E262C),
        surfaceContainerHigh = Color(0xFF283038),
        surfaceContainerHighest = Color(0xFF333C44),
    )

// ==================== Flower Whisper (花语) ====================

val PetalLightColorScheme =
    lightColorScheme(
        primary = Color(0xFFC2789A),
        onPrimary = Color(0xFFFFFFFF),
        primaryContainer = Color(0xFFFBEEF4),
        onPrimaryContainer = Color(0xFF4A2038),
        secondary = Color(0xFF6EB5A0),
        onSecondary = Color(0xFFFFFFFF),
        secondaryContainer = Color(0xFFECF6F2),
        onSecondaryContainer = Color(0xFF1E4438),
        tertiary = Color(0xFFD4977B),
        onTertiary = Color(0xFFFFFFFF),
        tertiaryContainer = Color(0xFFFDF2EC),
        onTertiaryContainer = Color(0xFF4A3020),
        error = Color(0xFFBA1A1A),
        onError = Color(0xFFFFFFFF),
        errorContainer = Color(0xFFFFDAD6),
        onErrorContainer = Color(0xFF410002),
        background = Color(0xFFFBF6F8),
        onBackground = Color(0xFF2C2028),
        surface = Color(0xFFFBF6F8),
        onSurface = Color(0xFF2C2028),
        surfaceVariant = Color(0xFFF3EAEE),
        onSurfaceVariant = Color(0xFF524448),
        outline = Color(0xFF857478),
        outlineVariant = Color(0xFFD8CDD0),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFF383035),
        inverseOnSurface = Color(0xFFF5EDEF),
        inversePrimary = Color(0xFFE0B0C4),
        surfaceDim = Color(0xFFE0D6DA),
        surfaceBright = Color(0xFFFBF6F8),
        surfaceContainerLowest = Color(0xFFFFFFFF),
        surfaceContainerLow = Color(0xFFF7F0F4),
        surfaceContainer = Color(0xFFF3EAEE),
        surfaceContainerHigh = Color(0xFFEDE4E8),
        surfaceContainerHighest = Color(0xFFE7DEE2),
    )

val PetalDarkColorScheme =
    darkColorScheme(
        primary = Color(0xFFD88AAE),
        onPrimary = Color(0xFF3E1028),
        primaryContainer = Color(0xFF4A2038),
        onPrimaryContainer = Color(0xFFFBEEF4),
        secondary = Color(0xFFB0D8C8),
        onSecondary = Color(0xFF0C3025),
        secondaryContainer = Color(0xFF1E4438),
        onSecondaryContainer = Color(0xFFECF6F2),
        tertiary = Color(0xFFE8C8B0),
        onTertiary = Color(0xFF3A2010),
        tertiaryContainer = Color(0xFF4A3020),
        onTertiaryContainer = Color(0xFFFDF2EC),
        error = Color(0xFFFFB4AB),
        onError = Color(0xFF690005),
        errorContainer = Color(0xFF93000A),
        onErrorContainer = Color(0xFFFFDAD6),
        background = Color(0xFF1C1418),
        onBackground = Color(0xFFEEDDE6),
        surface = Color(0xFF1C1418),
        onSurface = Color(0xFFEEDDE6),
        surfaceVariant = Color(0xFF3E3438),
        onSurfaceVariant = Color(0xFFD8CDD0),
        outline = Color(0xFF9E9094),
        outlineVariant = Color(0xFF3E3438),
        scrim = Color(0xFF000000),
        inverseSurface = Color(0xFFEEDDE6),
        inverseOnSurface = Color(0xFF383035),
        inversePrimary = Color(0xFFC2789A),
        surfaceDim = Color(0xFF1C1418),
        surfaceBright = Color(0xFF443840),
        surfaceContainerLowest = Color(0xFF160E12),
        surfaceContainerLow = Color(0xFF241C20),
        surfaceContainer = Color(0xFF282024),
        surfaceContainerHigh = Color(0xFF332A2F),
        surfaceContainerHighest = Color(0xFF3E353A),
    )
